---
parent: "api_v1_system-settings"
name: "ApiV1SystemSettingsGetNoParams"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings"
method: "GET"
auth: "Default"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode == 200"
tags:
- "V1"
authors:
- "FX Bot"
category: "SimpleGET"
severity: "Major"
inactive: false
policies: null
