---
parent: "api_v1_projects_@random_autocodeconfig"
name: "ApiV1Projects@randomAutocodeconfigGetOtherRbac"
description: null
type: "SUITE"
endpoint: "/api/v1/projects/{{@Random}}/autocodeconfig"
method: "GET"
auth: "Other"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode == 403"
tags:
- "V1"
authors:
- "FX Bot"
init: []
cleanup: []
category: "RBAC"
severity: "Critical"
inactive: false
policies: null
